/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamSignupRouteImport } from './routes/team-signup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsOrgIdRouteImport } from './routes/orgs.$orgId'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding.success'
import { Route as OnboardingSubscribeRouteImport } from './routes/onboarding.subscribe'
import { Route as OrgsOrgIdSettingsPeopleRouteImport } from './routes/orgs.$orgId.settings.people'
import { Route as OrgsOrgIdSettingsBillingRouteImport } from './routes/orgs.$orgId.settings.billing'

const TeamSignupRoute = TeamSignupRouteImport.update({
  id: '/team-signup',
  path: '/team-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdRoute = OrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSubscribeRoute = OnboardingSubscribeRouteImport.update({
  id: '/onboarding/subscribe',
  path: '/onboarding/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdSettingsPeopleRoute = OrgsOrgIdSettingsPeopleRouteImport.update({
  id: '/settings/people',
  path: '/settings/people',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdSettingsBillingRoute =
  OrgsOrgIdSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => OrgsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/team-signup': typeof TeamSignupRoute
  '/onboarding/subscribe': typeof OnboardingSubscribeRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/orgs/$orgId': typeof OrgsOrgIdRouteWithChildren
  '/orgs/$orgId/settings/billing': typeof OrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/people': typeof OrgsOrgIdSettingsPeopleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/team-signup': typeof TeamSignupRoute
  '/onboarding/subscribe': typeof OnboardingSubscribeRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/orgs/$orgId': typeof OrgsOrgIdRouteWithChildren
  '/orgs/$orgId/settings/billing': typeof OrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/people': typeof OrgsOrgIdSettingsPeopleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/team-signup': typeof TeamSignupRoute
  '/onboarding/subscribe': typeof OnboardingSubscribeRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/orgs/$orgId': typeof OrgsOrgIdRouteWithChildren
  '/orgs/$orgId/settings/billing': typeof OrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/people': typeof OrgsOrgIdSettingsPeopleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/team-signup'
    | '/onboarding/subscribe'
    | '/onboarding/success'
    | '/orgs/$orgId'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/people'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/team-signup'
    | '/onboarding/subscribe'
    | '/onboarding/success'
    | '/orgs/$orgId'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/people'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/team-signup'
    | '/onboarding/subscribe'
    | '/onboarding/success'
    | '/orgs/$orgId'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/people'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TeamSignupRoute: typeof TeamSignupRoute
  OnboardingSubscribeRoute: typeof OnboardingSubscribeRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OrgsOrgIdRoute: typeof OrgsOrgIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-signup': {
      id: '/team-signup'
      path: '/team-signup'
      fullPath: '/team-signup'
      preLoaderRoute: typeof TeamSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId': {
      id: '/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/subscribe': {
      id: '/onboarding/subscribe'
      path: '/onboarding/subscribe'
      fullPath: '/onboarding/subscribe'
      preLoaderRoute: typeof OnboardingSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/settings/people': {
      id: '/orgs/$orgId/settings/people'
      path: '/settings/people'
      fullPath: '/orgs/$orgId/settings/people'
      preLoaderRoute: typeof OrgsOrgIdSettingsPeopleRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/settings/billing': {
      id: '/orgs/$orgId/settings/billing'
      path: '/settings/billing'
      fullPath: '/orgs/$orgId/settings/billing'
      preLoaderRoute: typeof OrgsOrgIdSettingsBillingRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
  }
}

interface OrgsOrgIdRouteChildren {
  OrgsOrgIdSettingsBillingRoute: typeof OrgsOrgIdSettingsBillingRoute
  OrgsOrgIdSettingsPeopleRoute: typeof OrgsOrgIdSettingsPeopleRoute
}

const OrgsOrgIdRouteChildren: OrgsOrgIdRouteChildren = {
  OrgsOrgIdSettingsBillingRoute: OrgsOrgIdSettingsBillingRoute,
  OrgsOrgIdSettingsPeopleRoute: OrgsOrgIdSettingsPeopleRoute,
}

const OrgsOrgIdRouteWithChildren = OrgsOrgIdRoute._addFileChildren(
  OrgsOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TeamSignupRoute: TeamSignupRoute,
  OnboardingSubscribeRoute: OnboardingSubscribeRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OrgsOrgIdRoute: OrgsOrgIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
