/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamSignupRouteImport } from './routes/team-signup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsOrgIdSettingsPeopleRouteImport } from './routes/orgs.$orgId.settings.people'

const TeamSignupRoute = TeamSignupRouteImport.update({
  id: '/team-signup',
  path: '/team-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdSettingsPeopleRoute = OrgsOrgIdSettingsPeopleRouteImport.update({
  id: '/orgs/$orgId/settings/people',
  path: '/orgs/$orgId/settings/people',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/team-signup': typeof TeamSignupRoute
  '/orgs/$orgId/settings/people': typeof OrgsOrgIdSettingsPeopleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/team-signup': typeof TeamSignupRoute
  '/orgs/$orgId/settings/people': typeof OrgsOrgIdSettingsPeopleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/team-signup': typeof TeamSignupRoute
  '/orgs/$orgId/settings/people': typeof OrgsOrgIdSettingsPeopleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/team-signup'
    | '/orgs/$orgId/settings/people'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/team-signup'
    | '/orgs/$orgId/settings/people'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/team-signup'
    | '/orgs/$orgId/settings/people'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TeamSignupRoute: typeof TeamSignupRoute
  OrgsOrgIdSettingsPeopleRoute: typeof OrgsOrgIdSettingsPeopleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-signup': {
      id: '/team-signup'
      path: '/team-signup'
      fullPath: '/team-signup'
      preLoaderRoute: typeof TeamSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/settings/people': {
      id: '/orgs/$orgId/settings/people'
      path: '/orgs/$orgId/settings/people'
      fullPath: '/orgs/$orgId/settings/people'
      preLoaderRoute: typeof OrgsOrgIdSettingsPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TeamSignupRoute: TeamSignupRoute,
  OrgsOrgIdSettingsPeopleRoute: OrgsOrgIdSettingsPeopleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
