/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailsEntityIdRouteImport } from './routes/emails_.$entityId'
import { Route as AuditEntityIdRouteImport } from './routes/audit_.$entityId'
import { Route as OrgsEntityIdBillingRouteImport } from './routes/orgs_.$entityId.billing'

const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsEntityIdRoute = EmailsEntityIdRouteImport.update({
  id: '/emails_/$entityId',
  path: '/emails/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditEntityIdRoute = AuditEntityIdRouteImport.update({
  id: '/audit_/$entityId',
  path: '/audit/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsEntityIdBillingRoute = OrgsEntityIdBillingRouteImport.update({
  id: '/orgs_/$entityId/billing',
  path: '/orgs/$entityId/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/emails': typeof EmailsRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/audit/$entityId': typeof AuditEntityIdRoute
  '/emails/$entityId': typeof EmailsEntityIdRoute
  '/orgs/$entityId/billing': typeof OrgsEntityIdBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/emails': typeof EmailsRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/audit/$entityId': typeof AuditEntityIdRoute
  '/emails/$entityId': typeof EmailsEntityIdRoute
  '/orgs/$entityId/billing': typeof OrgsEntityIdBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/emails': typeof EmailsRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/audit_/$entityId': typeof AuditEntityIdRoute
  '/emails_/$entityId': typeof EmailsEntityIdRoute
  '/orgs_/$entityId/billing': typeof OrgsEntityIdBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/emails'
    | '/login'
    | '/orgs'
    | '/audit/$entityId'
    | '/emails/$entityId'
    | '/orgs/$entityId/billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/emails'
    | '/login'
    | '/orgs'
    | '/audit/$entityId'
    | '/emails/$entityId'
    | '/orgs/$entityId/billing'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/emails'
    | '/login'
    | '/orgs'
    | '/audit_/$entityId'
    | '/emails_/$entityId'
    | '/orgs_/$entityId/billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  EmailsRoute: typeof EmailsRoute
  LoginRoute: typeof LoginRoute
  OrgsRoute: typeof OrgsRoute
  AuditEntityIdRoute: typeof AuditEntityIdRoute
  EmailsEntityIdRoute: typeof EmailsEntityIdRoute
  OrgsEntityIdBillingRoute: typeof OrgsEntityIdBillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails_/$entityId': {
      id: '/emails_/$entityId'
      path: '/emails/$entityId'
      fullPath: '/emails/$entityId'
      preLoaderRoute: typeof EmailsEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit_/$entityId': {
      id: '/audit_/$entityId'
      path: '/audit/$entityId'
      fullPath: '/audit/$entityId'
      preLoaderRoute: typeof AuditEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs_/$entityId/billing': {
      id: '/orgs_/$entityId/billing'
      path: '/orgs/$entityId/billing'
      fullPath: '/orgs/$entityId/billing'
      preLoaderRoute: typeof OrgsEntityIdBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  EmailsRoute: EmailsRoute,
  LoginRoute: LoginRoute,
  OrgsRoute: OrgsRoute,
  AuditEntityIdRoute: AuditEntityIdRoute,
  EmailsEntityIdRoute: EmailsEntityIdRoute,
  OrgsEntityIdBillingRoute: OrgsEntityIdBillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
